### ISSUE TITLE
Export or Import problem

### ISSUE THREAD

**Issue by toome123** [SamirHodzic/ngx-youtube-player#2]
When i export playlist it's save to "text/plain" type, not to "application/json" [Link to export function](https://github.com/SamirHodzic/ngx-youtube-player/blob/master/src/app/main/main.component.ts#L184)
I thing the type specified in `	let file = new Blob([data], { type: "text/json" });` is wrong.. 
must be `"application/json"` ?
But  this it does not matter, because i tried to `"application/json"` and don't work.. 
And is show me "File is not supported."
I attached a screen photo of debug when i trying to import play list.

![importfileerror](https://cloud.githubusercontent.com/assets/2394224/23873131/a365c4bc-0839-11e7-9414-b97a58b712c2.png)

**Comment by SamirHodzic** [comment]
Problem with import, 
Seems like Chrome on Windows determine mime type as "" (empty string), on Linux as "text/plain".

Changed file type validation to the classic approach. e15978ec285e60431c7f162d3bca283b73d21909

Thanks for reporting, cheers.
