### ISSUE TITLE
Functionality problems on linux

### ISSUE THREAD

**Issue by aadeenr** [SamirHodzic/ngx-youtube-player#3]
On Ubuntu 16.04 LTS (tested on google chrome and firefox) your app is mostly not working:
- search doesn't work at all;
- when I add a video to my playlist I have to refresh the page to see the video in the playlist;
- should play button transform in a pause button when video is playing? Right now it's always a play button;
- repeat and shuffle are not working at all
- burger menu doesn't do anything on click
- fullscreen buton on player-controls-block doesn't work correctly (the video gets a little bigger in the left-bottom corner)
- video thumbnails are not loaded 

![image](https://cloud.githubusercontent.com/assets/16778341/24837230/05cbf726-1d38-11e7-94b5-17165df653cc.png)

![image](https://cloud.githubusercontent.com/assets/16778341/24837247/51c1d038-1d38-11e7-9db8-c6dff701b7db.png)

**Comment by SamirHodzic** [comment]
Strange issue, will investigate.

**Comment by SamirHodzic** [comment]
Fixed, seems like YouTube API statistics object is missing on some videos. 15daa2f3119eb0109c0b6299e5d9c24f7354c3bd

Thanks for reporting.
