### ISSUE TITLE
Loved your app! Can you convert it to angular 6 ?

### ISSUE THREAD

**Issue by jaydeepkarena** [SamirHodzic/ngx-youtube-player#9]
I am currently learning angular & found your app at [AngularExpo.com](https://angularexpo.com/youtube-player/). Your app is in Angular 5 and I am learning Angular 6, I wonder what changes should be made to this app to convert it to angular 6.

I don't no what should be changed, but if there are major changes than if you convert it to 6, than it will be very useful to people like who is learning angular.

**Comment by SamirHodzic** [comment]
Hi,
I can't promise, but will check out when I catch time.

**Comment by jaydeepkarena** [comment]
Thank you sir 👍

**Comment by SamirHodzic** [comment]
Updated to latest Angular.

Cheers.

**Comment by jaydeepkarena** [comment]
Thank You :+1:
